CREATE DATABASE test_adv;
USE test_adv;
CREATE TABLE departments (id INT PRIMARY KEY, name VARCHAR(50) UNIQUE NOT NULL);
INSERT INTO departments VALUES (1, 'Engineering');
INSERT INTO departments VALUES (2, 'HR');
INSERT INTO departments VALUES (3, 'Sales');
INSERT INTO departments VALUES (4, 'HR');
INSERT INTO departments (id) VALUES (5);
CREATE TABLE employees (id INT PRIMARY KEY, dept_id INT REFERENCES departments(id), name TEXT NOT NULL, status VARCHAR(20) DEFAULT 'ACTIVE');
INSERT INTO employees (id, dept_id, name) VALUES (101, 1, 'Alice');
INSERT INTO employees VALUES (102, 2, 'Bob', 'ON_LEAVE');
INSERT INTO employees VALUES (103, 99, 'Charlie', 'ACTIVE');
SELECT * FROM employees;
INSERT INTO employees VALUES (104, 1, 'Dave', 'ACTIVE');
INSERT INTO employees VALUES (105, 3, 'Eve', 'ACTIVE');
SELECT * FROM employees ORDER BY id ASC LIMIT 2 OFFSET 1;
SELECT name FROM employees WHERE dept_id IN (SELECT id FROM departments WHERE name = 'Engineering');
SELECT name FROM departments WHERE EXISTS (SELECT id FROM employees WHERE employees.dept_id = departments.id AND employees.status = 'ON_LEAVE');
ALTER TABLE employees DROP COLUMN status;
SELECT * FROM employees;
